apiVersion: apps/v1
kind: Deployment
metadata:
  name: household-inventory-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: household-inventory-quarkus
  template:
    metadata:
      labels:
        app: household-inventory-quarkus
    spec:
      containers:
      - name: household-inventory-quarkus
        image: GET_CONTAINER_IMAGE_AT_RUNTIME
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: household-inventory-lb
spec:
  selector:
    app: household-inventory-quarkus
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 8080
  type: LoadBalancer