/**
 * NOTE: This class is auto generated by the swagger code generator program (3.0.19).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package com.cresloga.inventory.household.householdinventory.api;

import java.math.BigDecimal;
import javax.ws.rs.Consumes;
import javax.ws.rs.DELETE;
import javax.ws.rs.GET;
import javax.ws.rs.PATCH;
import javax.ws.rs.POST;
import javax.ws.rs.PUT;
import javax.ws.rs.Path;
import javax.ws.rs.PathParam;
import javax.ws.rs.Produces;
import javax.ws.rs.core.MediaType;

import org.eclipse.microprofile.openapi.annotations.tags.Tag;

import com.cresloga.inventory.household.householdinventory.models.dto.GetAllResponse;
import com.cresloga.inventory.household.householdinventory.models.dto.GetResponse;
import com.cresloga.inventory.household.householdinventory.models.dto.Item;

@Path(value = "/quarkus")
@Tag(name="Groceries")
public interface GroceryV1Api {

	@Path(value = "/v2/groceries")
	@Produces(MediaType.APPLICATION_JSON)
	@Consumes(MediaType.APPLICATION_JSON)
	@POST
	void createV1(Item body);

	@Path(value = "/v2/groceries/{id}")
	@Produces(MediaType.APPLICATION_JSON)
	@DELETE
	void deleteByIdV1(@PathParam("id") Long id);

	@Path(value = "/v2/groceries")
	@Produces(MediaType.APPLICATION_JSON)
	@GET
	GetAllResponse getAllV1();

	@Path(value = "/v2/groceries/{id}")
	@Produces(MediaType.APPLICATION_JSON)
	@GET
	GetResponse getByIdV1(@PathParam("id") Long id);

	@Path(value = "/v2/groceries/{id}")
	@Produces(MediaType.APPLICATION_JSON)
	@Consumes(MediaType.APPLICATION_JSON)
	@PUT
	void replaceByIdV1(@PathParam("id") Long id, Item body);

	@Path(value = "/v2/groceries/{id}/quantity/{quantity}")
	@Produces(MediaType.APPLICATION_JSON)
	@PATCH
	void updateByIdV1(@PathParam("id") Long id, @PathParam("quantity") BigDecimal quantity);

}
